name: Build & publish

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      # https://stackoverflow.com/questions/32113330/check-if-imagetag-combination-already-exists-on-docker-hub
      - name: Ensure image isn't already published
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

          if DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect elrondnetwork/build-contract-rust:${GITHUB_REF_NAME} >/dev/null; then
              echo "Image already published. Will NOT publish."
              exit 1
          else
              echo "Image not yet published. Will publish."
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: elrondnetwork/build-contract-rust:${GITHUB_REF_NAME}
